*** Starting uWSGI 2.0.18 (64bit) on [Sat Mar 28 15:24:04 2020] ***
compiled with version: 7.3.0 on 23 February 2020 19:22:36
os: Linux-4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
nodename: programmer-G56JR
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /home/programmer/Project/lorean
detected binary path: /home/programmer/Project/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 47173
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/lorean.sock fd 3
Python version: 3.6.8 (default, Oct  7 2019, 12:59:55)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x563a01177830
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x563a01177830 pid: 9616 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 9616, cores: 1)
*** Starting uWSGI 2.0.18 (64bit) on [Sat Mar 28 15:25:21 2020] ***
compiled with version: 7.3.0 on 23 February 2020 19:22:36
os: Linux-4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
nodename: programmer-G56JR
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /home/programmer/Project/lorean
detected binary path: /home/programmer/Project/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 47173
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/lorean.sock fd 3
Python version: 3.6.8 (default, Oct  7 2019, 12:59:55)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55ad0126a830
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55ad0126a830 pid: 9669 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 9669, cores: 1)
[pid: 9669|app: 0|req: 1/1] 127.0.0.1 () {42 vars in 711 bytes} [Sat Mar 28 12:25:47 2020] GET / => generated 16351 bytes in 18 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Sat Mar 28 15:50:01 2020] ***
compiled with version: 7.3.0 on 23 February 2020 19:22:36
os: Linux-4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
nodename: programmer-G56JR
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /home/programmer/Project/lorean
detected binary path: /home/programmer/Project/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 47173
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/lorean.sock fd 3
Python version: 3.6.8 (default, Oct  7 2019, 12:59:55)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x556cade19840
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x556cade19840 pid: 11951 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 11951, cores: 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 544, in resolve
    for pattern in self.url_patterns:
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/programmer/Project/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./lorean/urls.py", line 18, in <module>
    from . import views
ImportError: cannot import name 'views'
[pid: 11951|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 12:50:05 2020] GET / => generated 102627 bytes in 60 msecs (HTTP/1.1 500) 5 headers in 157 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 544, in resolve
    for pattern in self.url_patterns:
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/programmer/Project/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./lorean/urls.py", line 18, in <module>
    from django.legion	import views
ModuleNotFoundError: No module named 'django.legion'
[pid: 11951|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 12:51:09 2020] GET / => generated 102719 bytes in 40 msecs (HTTP/1.1 500) 5 headers in 157 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 544, in resolve
    for pattern in self.url_patterns:
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/programmer/Project/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/programmer/Project/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./lorean/urls.py", line 18, in <module>
    from django.legion	import views
ModuleNotFoundError: No module named 'django.legion'
[pid: 11951|app: 0|req: 3/3] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 12:51:10 2020] GET / => generated 102719 bytes in 57 msecs (HTTP/1.1 500) 5 headers in 157 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 4/4] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 12:51:23 2020] GET / => generated 248 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 5/5] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 12:52:01 2020] GET / => generated 246 bytes in 1 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 6/6] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 12:53:02 2020] GET / => generated 246 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 7/7] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 12:59:36 2020] GET / => generated 246 bytes in 1 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 8/8] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 13:00:11 2020] GET / => generated 246 bytes in 1 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 9/9] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 13:28:08 2020] GET / => generated 246 bytes in 1 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 10/10] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 13:28:34 2020] GET / => generated 246 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 11/11] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 13:30:01 2020] GET / => generated 246 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 12/12] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 13:30:17 2020] GET / => generated 246 bytes in 1 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 13/13] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 13:30:26 2020] GET / => generated 246 bytes in 1 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 14/14] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 13:30:45 2020] GET / => generated 246 bytes in 1 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 15/15] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 13:30:45 2020] GET / => generated 246 bytes in 1 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 16/16] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 13:30:48 2020] GET / => generated 246 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
[pid: 11951|app: 0|req: 17/17] 127.0.0.1 () {44 vars in 742 bytes} [Sat Mar 28 13:31:02 2020] GET / => generated 246 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 136 bytes (1 switches on core 0)
